name = "YAMLScript"
uuid = "c6519b1f-f61a-46f8-9c82-37138c212585"
authors = ["Ingy d√∂t Net <ingy@ingy.net>"]
version = "0.1.76"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
julia = "1"
JSON = "0.21.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
